# Generated by Django 6.0.2 on 2026-02-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编号')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料分类',
                'verbose_name_plural': '材料分类',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('op_type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('export', '导出'), ('login', '登录'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(verbose_name='操作详情')),
                ('related_no', models.CharField(blank=True, max_length=50, verbose_name='关联单号')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('manager', models.CharField(blank=True, max_length=50, verbose_name='项目负责人')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='项目地点')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='预计竣工日期')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='项目预算')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完工'), ('paused', '暂停')], default='active', max_length=20, verbose_name='项目状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工程项目',
                'verbose_name_plural': '工程项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='供应商编号')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('main_type', models.CharField(blank=True, max_length=200, verbose_name='主营材料类型')),
                ('credit_rating', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般')], default='good', max_length=20, verbose_name='信用等级')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='合作开始日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='材料编号')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(choices=[('吨', '吨'), ('千克', '千克'), ('立方米', '立方米'), ('平方米', '平方米'), ('米', '米'), ('根', '根'), ('个', '个'), ('套', '套'), ('箱', '箱'), ('袋', '袋'), ('卷', '卷'), ('块', '块'), ('张', '张'), ('件', '件')], max_length=20, verbose_name='计量单位')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标准单价')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='安全库存量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.category', verbose_name='材料分类')),
            ],
            options={
                'verbose_name': '材料档案',
                'verbose_name_plural': '材料档案',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('operator', '操作员')], default='operator', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30, unique=True, verbose_name='出库单号')),
                ('date', models.DateField(verbose_name='出库日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='出库数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='成本单价')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总成本')),
                ('recipient', models.CharField(max_length=50, verbose_name='领用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='用途说明')),
                ('approver', models.CharField(blank=True, max_length=50, verbose_name='审批人')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='仓库位置')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_records', to='inventory.material', verbose_name='材料')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_records', to='inventory.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
                'ordering': ['-date', '-operate_time'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='计划编号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划采购数量')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预计单价')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预计总金额')),
                ('required_date', models.DateField(verbose_name='需求日期')),
                ('applicant', models.CharField(max_length=50, verbose_name='申请人')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('purchased', '已采购'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approver', models.CharField(blank=True, max_length=50, verbose_name='审批人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_plans', to='inventory.material', verbose_name='材料')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_plans', to='inventory.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '采购计划',
                'verbose_name_plural': '采购计划',
                'ordering': ['-apply_date'],
            },
        ),
        migrations.CreateModel(
            name='InboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30, unique=True, verbose_name='入库单号')),
                ('date', models.DateField(verbose_name='入库日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='入库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总金额')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='采购批次号')),
                ('inspector', models.CharField(blank=True, max_length=50, verbose_name='验收人')),
                ('quality_status', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格')], default='qualified', max_length=20, verbose_name='质量状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='仓库位置')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_records', to='inventory.material', verbose_name='材料')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_records', to='inventory.project', verbose_name='所属项目')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_records', to='inventory.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'ordering': ['-date', '-operate_time'],
            },
        ),
    ]
