# Generated by Django 6.0.2 on 2026-02-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasePlan',
        ),
    ]
