# Generated by Django 6.0.2 on 2026-02-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_purchaseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='main_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='inventory.category', verbose_name='主营材料类型'),
        ),
    ]
