# Generated by Django 6.0.2 on 2026-02-11 13:50

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    将供应商的主营材料类型从文本转换为分类外键
    """
    # 获取历史模型
    Supplier = apps.get_model('inventory', 'Supplier')
    Category = apps.get_model('inventory', 'Category')
    
    # 为每个供应商查找匹配的分类
    for supplier in Supplier.objects.all():
        if supplier.main_type:  # 如果原字段有值
            # 查找匹配的分类（按名称或代码）
            try:
                category = Category.objects.get(name=supplier.main_type)
                supplier.main_type_id = category.id
                supplier.save(update_fields=['main_type_id'])
            except Category.DoesNotExist:
                # 如果找不到匹配的分类，留空
                supplier.main_type_id = None
                supplier.save(update_fields=['main_type_id'])


def reverse_func(apps, schema_editor):
    """
    将供应商的主营材料类型从分类外键转换回文本
    """
    Supplier = apps.get_model('inventory', 'Supplier')
    Category = apps.get_model('inventory', 'Category')
    
    # 将分类ID转换回文本
    for supplier in Supplier.objects.all():
        if supplier.main_type:  # 如果有关联的分类
            supplier.main_type = supplier.main_type.name  # 使用分类名称
            supplier.save(update_fields=['main_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplier_main_type'),
    ]

    operations = [
        # 执行数据转换
        migrations.RunPython(forwards_func, reverse_func),
    ]