# Generated by Django 6.0.3 on 2026-03-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_supplier_main_type_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutboundRecord',
        ),
    ]
