# Generated by Django 6.0.3 on 2026-03-21 22:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_outboundrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目地址'),
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30, unique=True, verbose_name='计划编号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='采购数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='预计单价')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='预计金额')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '采购中'), ('shipping', '发货中'), ('received', '已入库')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划采购日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_plans', to='inventory.material', verbose_name='材料')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_plans', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_plans', to='inventory.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '采购计划',
                'verbose_name_plural': '采购计划',
                'ordering': ['-create_time'],
            },
        ),
    ]
