# Generated by Django 6.0.3 on 2026-03-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inboundrecord_location_purchaseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('material_dept', '物资部'), ('clerk', '材料员'), ('supplier', '供应商')], default='clerk', max_length=20, verbose_name='角色'),
        ),
    ]
