# Generated by Django 6.0.3 on 2026-03-21 22:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30, unique=True, verbose_name='发货单号')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='实际发货数量')),
                ('actual_unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='实际单价')),
                ('actual_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='实际金额')),
                ('shipping_method', models.CharField(choices=[('special', '专车'), ('logistics', '物流')], default='special', max_length=20, verbose_name='送货方式')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='车牌号')),
                ('tracking_no', models.CharField(blank=True, max_length=50, verbose_name='运单号')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/', verbose_name='二维码')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('received', '已收货')], default='pending', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('purchase_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.purchaseplan', verbose_name='采购计划')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='供应商')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单',
                'ordering': ['-create_time'],
            },
        ),
    ]
