# Generated by Django 6.0.3 on 2026-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrecord',
            name='spec',
            field=models.CharField(default='', max_length=100, verbose_name='规格型号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='location',
            field=models.CharField(max_length=100, verbose_name='项目地址'),
        ),
    ]
