# Generated by Django 6.0.3 on 2026-03-22 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inboundrecord_spec_alter_inboundrecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='supplier_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='inventory.supplier', verbose_name='关联供应商档案'),
        ),
    ]
