# Generated by Django 6.0.3 on 2026-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='location',
            field=models.CharField(max_length=100, verbose_name='项目地址（快照）'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='spec',
            field=models.CharField(max_length=100, verbose_name='规格型号（快照）'),
        ),
    ]
