# Generated by Django 6.0.3 on 2026-03-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_soft_delete_and_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='qr_code',
        ),
    ]
