# Generated by Django 6.0.3 on 2026-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_delivery_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', '筹备中'), ('active', '进行中'), ('completed', '已完工'), ('paused', '暂停')], default='active', max_length=20, verbose_name='项目状态'),
        ),
    ]
