# Generated by Django 6.0.3 on 2026-03-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_soft_delete_to_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.supplier', verbose_name='供应商'),
        ),
    ]
