# Generated by Django 6.0.3 on 2026-03-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_delivery_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('received', '已收货')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='date',
            field=models.DateField(db_index=True, verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='status',
            field=models.CharField(choices=[('pending', '审批中'), ('approved', '采购中'), ('shipping', '发货中'), ('received', '已入库')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
