# Generated by Django 6.0.3 on 2026-03-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_delivery_status_alter_inboundrecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='purchaseplan',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已删除'),
        ),
    ]
