# Generated by Django 6.0.3 on 2026-03-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_soft_delete_to_category_and_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_plans', to='inventory.supplier', verbose_name='供应商'),
        ),
    ]
