# Generated by Django 6.0.3 on 2026-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_management_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='spec',
            field=models.CharField(default='', max_length=200, verbose_name='规格型号'),
        ),
    ]
