# Generated by Django 6.0.3 on 2026-03-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_missing_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='delivery',
            name='inventory_delivery_purchase_plan_idx',
        ),
        migrations.RemoveIndex(
            model_name='delivery',
            name='inventory_delivery_supplier_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboundrecord',
            name='inventory_inboundrecord_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboundrecord',
            name='inventory_inboundrecord_material_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='inventory_material_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseplan',
            name='inventory_purchaseplan_project_material_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='inventory_supplier_main_type_idx',
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='status',
            field=models.CharField(choices=[('pending', '审批中'), ('approved', '采购中'), ('shipping', '发货中'), ('shipped', '已发货'), ('received', '已入库')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
