# Generated by Django 6.0.3 on 2026-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_delivery_inventory_delivery_purchase_plan_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplan',
            name='status',
            field=models.CharField(choices=[('pending', '审批中'), ('shipping', '发货中'), ('shipped', '已发货'), ('received', '已入库')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
