# Generated by Django 6.0.3 on 2026-03-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_additional_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='delivery',
            name='inventory_delivery_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboundrecord',
            name='inventory_inboundrecord_material_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='inventory_material_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='inventory_material_spec_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='inventory_project_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseplan',
            name='inventory_purchaseplan_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='inventory_supplier_name_idx',
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='status',
            field=models.CharField(choices=[('pending', '审批中'), ('purchasing', '采购中'), ('shipped', '已发货'), ('received', '已入库')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.RemoveField(
            model_name='inboundrecord',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
