# Generated by Django 6.0.3 on 2026-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_delivery_inventory_delivery_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('management', '管理层'), ('supplier', '供应商')], default='management', max_length=20, verbose_name='角色'),
        ),
    ]
