# Generated by Django 6.0.3 on 2026-04-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='清单编号')),
                ('name', models.CharField(max_length=200, verbose_name='清单名称')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('construction_params', models.CharField(max_length=200, verbose_name='施工参数')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='参考单价')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分包清单',
                'verbose_name_plural': '分包清单',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=200, verbose_name='分包商名称')),
                ('contact', models.CharField(max_length=50, verbose_name='负责人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('main_type', models.CharField(max_length=100, verbose_name='主营类型')),
                ('credit_rating', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般')], default='good', max_length=20, verbose_name='信用等级')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分包商',
                'verbose_name_plural': '分包商',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='项目预算'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='竣工日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目负责人'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='inventory.project', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '分包预算',
                'verbose_name_plural': '分包预算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='合同编号')),
                ('name', models.CharField(max_length=200, verbose_name='合同名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='inventory.project', verbose_name='项目名称')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='inventory.subcontractor', verbose_name='分包商')),
            ],
            options={
                'verbose_name': '分包合同',
                'verbose_name_plural': '分包合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='计量编号')),
                ('period_start', models.DateField(verbose_name='计量周期开始')),
                ('period_end', models.DateField(verbose_name='计量周期结束')),
                ('previous_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='之前产值')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='本期产值')),
                ('cumulative_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计产值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='inventory.contract', verbose_name='合同名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='inventory.project', verbose_name='项目名称')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='inventory.subcontractor', verbose_name='分包商')),
            ],
            options={
                'verbose_name': '进度计量',
                'verbose_name_plural': '进度计量',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='结算编号')),
                ('period_start', models.DateField(verbose_name='结算周期开始')),
                ('period_end', models.DateField(verbose_name='结算周期结束')),
                ('measurement_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='计量产值')),
                ('deduction_reason', models.CharField(max_length=200, verbose_name='扣款原因')),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='扣款金额')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='最终结算额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='inventory.contract', verbose_name='合同名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='inventory.project', verbose_name='项目名称')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='inventory.subcontractor', verbose_name='分包商')),
            ],
            options={
                'verbose_name': '分包结算',
                'verbose_name_plural': '分包结算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField(verbose_name='清单序号')),
                ('measurement_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='计量汇总工程量')),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='修正后工程量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='最终产值')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='inventory.settlement')),
                ('subcontract_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcontractlist', verbose_name='清单名称')),
            ],
            options={
                'verbose_name': '结算清单',
                'verbose_name_plural': '结算清单',
                'ordering': ['settlement', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField(verbose_name='清单序号')),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='之前工程量')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本期工程量')),
                ('cumulative_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计工程量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='本期产值')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_items', to='inventory.measurement')),
                ('subcontract_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_items', to='inventory.subcontractlist', verbose_name='清单名称')),
            ],
            options={
                'verbose_name': '计量清单',
                'verbose_name_plural': '计量清单',
                'ordering': ['measurement', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField(verbose_name='清单序号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='工程量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='合价')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='inventory.contract')),
                ('subcontract_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcontractlist', verbose_name='清单名称')),
            ],
            options={
                'verbose_name': '合同清单',
                'verbose_name_plural': '合同清单',
                'ordering': ['contract', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField(verbose_name='清单序号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='工程量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='合价')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='inventory.budget')),
                ('subcontract_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcontractlist', verbose_name='清单名称')),
            ],
            options={
                'verbose_name': '预算清单',
                'verbose_name_plural': '预算清单',
                'ordering': ['budget', 'item_order'],
            },
        ),
    ]
