# Generated by Django 6.0.3 on 2026-04-10 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_subcontractlist_subcontractor_alter_project_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('plan_number', models.CharField(max_length=100, unique=True, verbose_name='计划编号')),
                ('plan_date', models.DateField(default=django.utils.timezone.now, verbose_name='计划日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='计划总金额')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '材料计划',
                'verbose_name_plural': '材料计划管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='材料')),
                ('material_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialplan', verbose_name='材料计划')),
            ],
            options={
                'verbose_name': '材料计划明细',
                'verbose_name_plural': '材料计划明细管理',
            },
        ),
    ]
