# Generated by Django 6.0.3 on 2026-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_materialplan_materialplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, related_name='subcontractors', to='inventory.profile', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('management', '管理层'), ('supplier', '供应商'), ('subcontractor', '分包商')], default='management', max_length=20, verbose_name='角色'),
        ),
    ]
