# Generated by Django 6.0.3 on 2026-04-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_material_deleted_at_material_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='material_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_plans', to='inventory.materialplan', verbose_name='关联材料计划'),
        ),
    ]
