# Generated by Django 6.0.3 on 2026-04-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_purchaseplan_material_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='subcontract_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='inventory.subcontractlist', verbose_name='清单名称'),
        ),
    ]
