# Generated by Django 6.0.3 on 2026-04-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_contractitem_subcontract_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编号')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分包清单分类',
                'verbose_name_plural': '分包清单分类',
                'ordering': ['code'],
            },
        ),
    ]
