# Generated by Django 6.0.3 on 2026-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_subcontractcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractcategory',
            options={'ordering': ['category_code'], 'verbose_name': '分包清单分类', 'verbose_name_plural': '分包清单分类'},
        ),
        migrations.RemoveField(
            model_name='subcontractcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subcontractcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='subcontractcategory',
            name='category_code',
            field=models.CharField(default='BAT0000', max_length=20, unique=True, verbose_name='分类编码'),
        ),
        migrations.AddField(
            model_name='subcontractcategory',
            name='category_name',
            field=models.CharField(default='默认分类', max_length=100, verbose_name='分类名称'),
        ),
    ]
