# Generated by Django 6.0.3 on 2026-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_subcontractcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractcategory',
            name='category_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='分类编码'),
        ),
        migrations.AlterField(
            model_name='subcontractcategory',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='subcontractlist',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
