# Generated by Django 6.0.3 on 2026-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_subcontractcategory_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
